# Generated by Django 2.2.10 on 2020-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('designation', models.CharField(max_length=100)),
                ('phonenumber', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F')], max_length=6)),
            ],
        ),
    ]
